name: Check Output Branch Exists

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  check-output-branch:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Configure Git Identity
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Ensure the 'output' branch exists
      - name: Create Output Branch if Not Exists
        id: create_output_branch
        run: |
          # Check if the 'output' branch exists
          if ! git show-ref --verify --quiet refs/heads/output; then
            echo "Creating 'output' branch..."
            git checkout --orphan output
            git rm -rf .
            echo "This branch is used for GitHub Pages deployment" > README.md
            git add README.md
            git commit -m "Initial commit for output branch"
            git push origin output --force # Force push to overwrite the remote branch
          else
            echo "'output' branch already exists."
          fi
